version: '3.8'

services:

  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongo-server
    networks:
      - jwt-project
    ports:
      - 3001:3001
    # restart: unless-stopped
    environment:
      - API_PORT=3001
      - MONGO_URI=mongodb://mongo-server/n69ut?authSource=admin
  mongo-server:
    image: mongo:latest
    volumes:
      - ./data:/data
    networks:
      - jwt-project
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  jwt-project:
